name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Show current version of xcode CLI
        run: xcode-select -p
      - name: build and test
        run: xcodebuild clean test -scheme test.first -destination 'platform=macOS'
